/*
 * This source file was generated by the Gradle 'init' task
 * Desenvolvido por Igor da Silva
*/
package ifsc.poo;
import java.util.Random;

public class App {
    
    final static int MAX_RETANGULO = 10; // constante para testar a lista de retangulos

    static void testarDuasLampadas(){

        // LAMPADA A
        Lampada lampada_A = new Lampada();
        String ligada_A = lampada_A.verEstado() == true ? "Ligada" : "Desligada";
        System.out.println("Lampada A: " + ligada_A);

        if(lampada_A.ligar())
            System.out.println("Ligou A");
        else System.out.println("Desligou A");

        // LAMPADA B
        Lampada lampada_B = new Lampada(true);
        String ligada_B = lampada_B.verEstado() == true ? "Ligada" : "Desligada";
        System.out.println(ligada_B);

        System.out.println("" + Lampada.getQuantidadeLampadas());
    }


    static void testarDuasPessoas(){

        Pessoa pessoa_A = new Pessoa();
        pessoa_A.setNome("   AlICE    ");
        pessoa_A.setIdade(22);
        
        System.out.println("PESSOA_A:");
        System.out.println("Nome: " + pessoa_A.getNome());
        System.out.println("Idade: " + pessoa_A.getIdade());
        System.out.println("CPF: " + pessoa_A.getCpf());

        // ====== PESSOA_B ======
        Pessoa pessoa_B = new Pessoa("111.222.333-44", "   BRUnO  ", 25);
        for(int i = 0; i < 3; i++)
            pessoa_B.felizAniversario();

        System.out.println("\nPESSOA_B:");
        System.out.println("Nome: " + pessoa_B.getNome());
        System.out.println("Idade: " + pessoa_B.getIdade());
        System.out.println("CPF: " + pessoa_B.getCpf());

    }

    static void testarUmRetangulo(){

        Retangulo retangulo = new Retangulo();

        retangulo.setAltura(-2f);
        retangulo.setLargura(5f);

        System.out.println("Área: " + retangulo.getArea());
        System.out.println("Perímetro: " + retangulo.getPerimetro());

    }

    static void testarListaRetangulo(){

        Random numero = new Random();

        Retangulo[] lista_retangulos = new Retangulo[MAX_RETANGULO];
        float maiorRazao = 0f;
        int index = 0;

        for(int i = 0; i < MAX_RETANGULO; i++){

            lista_retangulos[i] = new Retangulo();
            lista_retangulos[i].setAltura((float) numero.nextInt(100));
            lista_retangulos[i].setLargura((float) numero.nextInt(100));

            if(maiorRazao < (lista_retangulos[i].getArea() / lista_retangulos[i].getPerimetro())){
                maiorRazao = (lista_retangulos[i].getArea() / lista_retangulos[i].getPerimetro());
                index = i;
            }

        }

        System.out.println("Maior razao: " + maiorRazao + " Posição na lista: " + index);

    }

    static void testarRelogio(){

        Relogio horario = new Relogio();

        // Obrigatorio os casting, do contrário não compila...
        horario.ajustaHora((byte) 22, (byte) 59, (byte) 59);

        //System.out.println(horario.getHora());

        //horario.avancaSegundo();
        //horario.avancaMinuto();
        //horario.avancaHora();

        System.out.println(horario.getHora());

        System.out.println(horario.getHoraFormatoV2());

    }

    static void testarProduto(){

        Produto p1 = new Produto();
        p1.setNome("    gelADeiRa   ");
        p1.setDesconto(6);
        p1.setPreco(832);

        Produto p2 = new Produto();
        p2.setDesconto(12);
        p2.setNome("    \n\n\n");
        p2.setPreco(499);

        System.out.println(p1.getNome() + ": " + p1.getPreco() + " reais");
        System.out.println(p2.getNome() + ": " + p2.getPreco() + " reais\n");

        System.out.println(p1.anuncio());
        System.out.println(p2.anuncio());

    }

    static void testarLivro(){

        Livro livro = new Livro();

        livro.setAutor("J. R. R. Tolkien");
        livro.setTitulo("O Senhor dos Anéis - A Sociedade do Anel");
        livro.setGeneroLiterario("Fantasia", "Aventura");
        livro.setTotalPagina(464);     

        System.out.println(livro.getGeneroLiterario());
        System.out.println(livro.getAutor());
        System.out.println(livro.getTitulo());

        // Setando nome dos capitulos...
        String[] nomeCaps = {"Uma festa Muito Esperada", "A Sombra do Passado", "Três é Demais",
                             "Um atalho para Cogumelos", "Uma conspiração Desmascarada", "A Floresta Velha",
                             "Em Casa de Tom Bombadil", "Névoa nas Colinas dos Túmulos", "No Pônei Empinado",
                             "Passolargo", "Um Faca na Noite", "Voo para o Vau", "Muitos Encontros",
                             "O Conselho de Elrond", "O anel Vai para o Sul", "Uma Jornada no Escuro",
                             "A ponte de Khazad-dûm", "Lothlórien", "O Espelho de Galadriel", "Adeus a Lórien", 
                             "O Grande Rio", "A Partida da Sociedade"};                            
        
        int[] inicioCaps = {1, 23, 44, 66, 89, 110, 131, 154, 176, 197, 219, 240, 261, 282, 301,
                            320, 341, 361, 383, 403, 423, 446};
    
        livro.setInicioCapitulos(inicioCaps);
        livro.setTituloCadaCapitulo(nomeCaps); 
        livro.imprimeSumario();
        
        livro.lerPaginas(90);
        System.out.println(livro.getCapituloAtual());

        livro.lerPaginas(300);
        System.out.println(livro.getCapituloAtual());
        
        livro.lerPaginas(100);
        System.out.println(livro.getCapituloAtual());
    }

    public static void main(String[] args) {

        /* ===== LEIA ABAIXO =====
        * SUGESTÃO: teste um de cada vez para não confundir a análise
        * e/ou poluir o prompt
        * "DESCOMENTE" o que deseja testar...
        */

        // ===== DESCOMENTE 'UM' MÉTODO ABAIXO PARA TESTAR O QUE DESEJA ===== 
        // testarDuasLampadas();
         testarDuasPessoas();
        // testarUmRetangulo();
        // testarListaRetangulo();
        // testarRelogio();
        // testarProduto();
        // testarLivro();

    }

}