/*
 * This source file was generated by the Gradle 'init' task
 * Desenvolvido por Igor da Silva
*/
package ifsc.poo;

import java.util.Random;

public class App {
    
    static void testarDuasLampadas(){

        // LAMPADA A
        Lampada lampada_A = new Lampada();
        lampada_A.ligar();
        lampada_A.verEstado();
        String ligada_A = lampada_A.verEstado() == true ? "1" : "0";
        System.out.println(ligada_A);

        // LAMPADA B
        Lampada lampada_B = new Lampada();
        lampada_B.desligar();
        lampada_B.verEstado();
        String ligada_B = lampada_B.verEstado() == true ? "1" : "0";
        System.out.println(ligada_B);

    }


    static void testarDuasPessoas(){

        Pessoa pessoa_A = new Pessoa();
        pessoa_A.setNome("Alice");
        pessoa_A.setIdade(22);
        
        System.out.println("Nome: " + pessoa_A.getNome() + "; Idade: " + pessoa_A.getIdade());

        Pessoa pessoa_B = new Pessoa();
        pessoa_B.setNome("Bruno");
        pessoa_B.setIdade(-25);
        for(int i = 0; i < 3; i++)
            pessoa_B.felizAniversario();

        System.out.println("Nome: " + pessoa_B.getNome() + "; Idade: " + pessoa_B.getIdade());

    }

    static void testarUmRetangulo(){

        Retangulo retangulo = new Retangulo();

        retangulo.setAltura(-2f);
        retangulo.setLargura(5f);

        System.out.println("Área: " + retangulo.getArea());
        System.out.println("Perímetro: " + retangulo.getPerimetro());

    }

     static void testarListaRetangulo(){

        Random numero = new Random();

        Retangulo[] lista_retangulos = new Retangulo[10];
        float maiorRazao = 0f;
        int index = 0;

        for(int i = 0; i < 10; i++){

            lista_retangulos[i] = new Retangulo();
            lista_retangulos[i].setAltura((float) numero.nextInt(100));
            lista_retangulos[i].setLargura((float) numero.nextInt(100));

            if(maiorRazao < (lista_retangulos[i].getArea() / lista_retangulos[i].getPerimetro())){
                maiorRazao = (lista_retangulos[i].getArea() / lista_retangulos[i].getPerimetro());
                index = i;
            }

        }

        System.out.println("Maior razao: " + maiorRazao + " Posição na lista: " + index);

    }

    static void testarRelogio(){

        Relogio horario = new Relogio();

        horario.ajustaHora((byte) 23, (byte) 59, (byte) 59);

        System.out.println(horario.getHora());

        horario.avancaSegundo();

        System.out.println(horario.getHora());

    }

    public static void main(String[] args) {

        // testarDuasLampadas();
        // testarDuasPessoas();
        // testarUmRetangulo();
         testarListaRetangulo();
        // testarRelogio();

    }

}