/*
 * This source file was generated by the Gradle 'init' task
 * Desenvolvido por Igor da Silva
*/
package ifsc.poo;
import java.util.Random;

public class App {
    
    final static int MAX_RETANGULO = 10; // constante para testar a lista de retangulos

    static void testarDuasLampadas(){

        // LAMPADA A
        Lampada lampada_A = new Lampada();
        lampada_A.ligar();
        lampada_A.verEstado();
        String ligada_A = lampada_A.verEstado() == true ? "1" : "0";
        System.out.println(ligada_A);

        // LAMPADA B
        Lampada lampada_B = new Lampada();
        lampada_B.desligar();
        lampada_B.verEstado();
        String ligada_B = lampada_B.verEstado() == true ? "1" : "0";
        System.out.println(ligada_B);

    }


    static void testarDuasPessoas(){

        Pessoa pessoa_A = new Pessoa();
        pessoa_A.setNome("   AlICE    ");
        pessoa_A.setIdade(22);
        
        System.out.println("Nome: " + pessoa_A.getNome() + "; Idade: " + pessoa_A.getIdade());

        Pessoa pessoa_B = new Pessoa();
        pessoa_B.setNome("Bruno");
        pessoa_B.setIdade(-25);

        // Bruno faz aniversário 3 vezes...
        for(int i = 0; i < 3; i++)
            pessoa_B.felizAniversario();

        System.out.println("Nome: " + pessoa_B.getNome() + "; Idade: " + pessoa_B.getIdade());

    }

    static void testarUmRetangulo(){

        Retangulo retangulo = new Retangulo();

        retangulo.setAltura(-2f);
        retangulo.setLargura(5f);

        System.out.println("Área: " + retangulo.getArea());
        System.out.println("Perímetro: " + retangulo.getPerimetro());

    }

    static void testarListaRetangulo(){

        Random numero = new Random();

        Retangulo[] lista_retangulos = new Retangulo[MAX_RETANGULO];
        float maiorRazao = 0f;
        int index = 0;

        for(int i = 0; i < MAX_RETANGULO; i++){

            lista_retangulos[i] = new Retangulo();
            lista_retangulos[i].setAltura((float) numero.nextInt(100));
            lista_retangulos[i].setLargura((float) numero.nextInt(100));

            if(maiorRazao < (lista_retangulos[i].getArea() / lista_retangulos[i].getPerimetro())){
                maiorRazao = (lista_retangulos[i].getArea() / lista_retangulos[i].getPerimetro());
                index = i;
            }

        }

        System.out.println("Maior razao: " + maiorRazao + " Posição na lista: " + index);

    }

    static void testarRelogio(){

        Relogio horario = new Relogio();

        // Obrigatorio os casting, do contrário não compila...
        horario.ajustaHora((byte) 22, (byte) 59, (byte) 59);

        //System.out.println(horario.getHora());

        //horario.avancaSegundo();
        //horario.avancaMinuto();
        //horario.avancaHora();

        System.out.println(horario.getHora());

        System.out.println(horario.getHoraFormatoV2());

    }

    static void testarProduto(){

        Produto p1 = new Produto();
        p1.setNome("    gelADeiRa   ");
        p1.setDesconto(6);
        p1.setPreco(832);

        Produto p2 = new Produto();
        p2.setDesconto(12);
        p2.setNome("    \n\n\n");
        p2.setPreco(499);

        System.out.println(p1.getNome() + ": " + p1.getPreco() + " reais");
        System.out.println(p2.getNome() + ": " + p2.getPreco() + " reais\n");

        System.out.println(p1.anuncio());
        System.out.println(p2.anuncio());

    }

    static void testarLivro(){

        Livro livro = new Livro();

        livro.setAutor("Igor da Silva");
        livro.setTitulo("Engenharia de Telecomunicações");
        livro.setGeneroLiterario("AVENturA");
        livro.setTotalPagina(586);     

        System.out.println(livro.getGeneroLiterario());
        System.out.println(livro.getAutor());
        System.out.println(livro.getTitulo());

    }

    public static void main(String[] args) {

        /* ===== LEIA ABAIXO =====
        * SUGESTÃO: teste um de cada vez para não confundir a análise
        * e/ou poluir o prompt
        * "DESCOMENTE" o que deseja testar...
        */

        // ===== DESCOMENTE 'UM' MÉTODO ABAIXO PARA TESTAR O QUE DESEJA ===== 
        // testarDuasLampadas();
        // testarDuasPessoas();
        // testarUmRetangulo();
        // testarListaRetangulo();
        // testarRelogio();
        // testarProduto();
        // testarLivro();

    }

}